version: "3.8"

services:
  contract-backend:
    image: contract-backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/output:/app/output
    restart: always

  contract-frontend:
    image: contract-frontend:latest
    container_name: frontend
    ports:
      - "1234:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    restart: always

  contract_mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
      - TZ=Asia/Shanghai
    command: --default-time-zone='+08:00'
    ports:
      - "3307:3306"
    restart: always
